### ISSUE TITLE
bug: `fan-in.js` file missing

### ISSUE THREAD

**Issue by dryajov** [push-stream/push-stream#4]
When running the tests I get this error:

```
Error: Cannot find module '../fan-in'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/dryajov/personal/projects/push-stream/test/fan-in.js:1:75)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

**Comment by dominictarr** [comment]
fixed in 10.0.4
